#!/usr/bin/env sh
#              _           _          
#             | |         (_)         
#  _   _  __ _| |__   __ _ _ _ __ ___ 
# | | | |/ _` | '_ \ / _` | | '__/ __|
# | |_| | (_| | |_) | (_| | | | | (__ 
#  \__, |\__,_|_.__/ \__,_|_|_|  \___|
#   __/ |                             
#  |___/                              

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  07
yabai -m config bottom_padding               07
yabai -m config left_padding                 07
yabai -m config right_padding                07
yabai -m config window_gap                   07

# Spaces
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five

# float preferences
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Zoom$" manage=off
yabai -m rule --add app="^Preview$" manage=off

# global settings
yabai -m config status_bar                   on
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config external_bar all:26:0

echo "yabai configuration loaded.."
