#!/usr/bin/env sh

#                           _                         
#                          | |                        
#  ___ _ __   __ _  ___ ___| |__   __ _ _ __ _ __ ___ 
# / __| '_ \ / _` |/ __/ _ \ '_ \ / _` | '__| '__/ __|
# \__ \ |_) | (_| | (_|  __/ |_) | (_| | |  | | | (__ 
# |___/ .__/ \__,_|\___\___|_.__/ \__,_|_|  |_|  \___|
#     | |                                             
#     |_|                    

spacebar -m config position             top
spacebar -m config height               26
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "MesloLGS NF:Regular:13.0"
spacebar -m config icon_font            "MesloLGS NF:Regular:13.0"
spacebar -m config right_shell          on
spacebar -m config right_shell_command  "whoami"
spacebar -m config right_shell_icon     
spacebar -m config right_shell_icon_color 0xffebdbb2
spacebar -m config background_color     0xff282828
spacebar -m config foreground_color     0xffebdbb2
spacebar -m config space_icon_color     0xfffb4934
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xff83a598
spacebar -m config clock_icon_color     0xffebdbb2
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip     I II III IV V VI VII VIII IX X
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%m/%d/%y %R"

echo "spacebar configuration loaded.."
